# образ запуска, должен быть на хост-машине
image: rust:1.92-alpine3.22

# переменные окружения конвейера
variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  PROJECT_DIR: "./cicd-rust/src/"

# Кеширование зависимостей ускорит последующие сборки
cache:
  paths:
    - .cargo/
    - ./cicd-rust/src/target/

# выполняется перед каждой задачей
before_script:
  - echo "Скрипт до основных инструкций (в каждой задаче)"
  - cd $PROJECT_DIR

# шаблон повторяющихся действий
.default_template:
  script:
    - echo "Executing script"

# выполняется после каждой задачи
after_script:
  - echo "Скрипт после основных инструкций (в каждой задаче)"

# типы задач
stages:
  # - lint
  - test
  - build
  - deploy

# # Проверка форматирования и синтаксиса
# linting:
#   stage: lint
#   script:
#     - rustup component add rustfmt clippy
#     - cargo fmt --check
#     - cargo clippy -- -D warnings

# сначала описан build, но первым выполнится test
build-release:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - ./cicd-rust/src/target/release/cicd-rust # Замените на имя вашего бинарника
    expire_in: 1 week

# # тесты
# unit-tests:
#   stage: test
#   script:
#     - cargo test --verbose

# сам деплой, включает сохранение артефакта в результаты конвейера
# Выгрузка в релизы (Generic Packages или Releases)
# Примечание: В GitFlic выгрузка в разделы "Релизы" часто требует API-вызова
deploy-1:
  stage: deploy
  needs:
    - build-release
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      # - if: $CI_COMMIT_TAG # Запускать только при создании тега (версии)
      # ручной запуск деплоя (последняя линия обороны, ответственность на человеке)
      when: manual
      # when: on_success # или вообще убрать, он по умолчанию
  before_script:
    - echo "Переопределение before_script"
    - cd $PROJECT_DIR
  script:
    - echo "Выгрузка артефакта для версии $CI_COMMIT_TAG"
    # Здесь обычно используется curl для загрузки в Generic Packages GitFlic
    # Или просто сохранение артефакта с длительным сроком хранения
  artifacts:
    paths:
      - ./cicd-rust/src/target/release/cicd-rust
