variables:
  APP_NAME: cicd-example

image: rust:${RUST_VERSION}-alpine${ALPINE_VERSION}

stages:
  - lint
  - test
  - deploy

linting:
  stage: lint
  rules:
    - if: $CI_COMMIT_REF_NAME
  script:
    - rustup component add rustfmt clippy
    - cargo fmt --check
    - cargo clippy -- -D warnings

tests:
  stage: test
  rules:
    - if: $CI_COMMIT_REF_NAME
  script:
    - cargo test --verbose

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
      when: manual

    - if: $CI_COMMIT_REF_NAME == "main"
      when: on_success

    - if: $CI_COMMIT_REF_NAME
      when: manual
      allow_failure: true
  image: docker:${DOCKER_VERSION}
  script:
    - export RELEASE_VERSION=${CI_COMMIT_TAG:-latest}
    - echo "Выгрузка артефакта для версии $RELEASE_VERSION"
    - mkdir -p artifacts_out
    - echo "Версия - $RELEASE_VERSION" > artifacts_out/artifact.txt
    - echo "Сообщение - $CI_COMMIT_MESSAGE" >> artifacts_out/artifact.txt
    - echo "Хеш - $CI_COMMIT_SHA" >> artifacts_out/artifact.txt
    - echo "Время - $CI_COMMIT_TIMESTAMP" >> artifacts_out/artifact.txt
    - echo "Ветка - $CI_COMMIT_REF_NAME" >> artifacts_out/artifact.txt
    - echo "Юзер - $GITFLIC_USER_EMAIL" >> artifacts_out/artifact.txt
    - echo "Карго - $CARGO_HOME" >> artifacts_out/artifact.txt
    - echo "Корень - $PROJECT_DIR" >> artifacts_out/artifact.txt

    # Здесь обычно используется curl для загрузки в Generic Packages GitFlic

    - export IMAGE_TAG=${CI_COMMIT_TAG:-latest}
    - >
      docker build 
      --build-arg RUST_VERSION=${RUST_VERSION}
      --build-arg ALPINE_VERSION=${ALPINE_VERSION}
      -t ${APP_NAME}:${IMAGE_TAG} .
    - docker save ${APP_NAME}:${IMAGE_TAG} > ${APP_NAME}.tar
  artifacts:
    paths:
      - artifacts_out/artifact.txt
      - "*.tar"
    expire_in: 1 week
  after_script:
    - docker image prune -f
