services:
  app:
    image: cicd:dev
    restart: no
    build:
      context: ./src/
      dockerfile: ../Dockerfile
      args:
        RUST_VERSION: 1.92
        ALPINE_VERSION: 3.22
        APP_NAME: cicd
        OUT_NAME: server
    ports:
      - "${APP_SERVER_PORT}:3000"
    environment:
      RUST_LOG: info
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 256M
        reservations:
          cpus: 0.5
          memory: 128M
    networks:
      - miku

  # postgres:
  #   container_name: postgreSQL
#     extends:
#       service: postgres
#       file: services-postgres.yaml
#     networks:
#       - miku

#   pgAdmin:
#     container_name: pgAdmin
#     extends:
#       service: pgAdmin
#       file: services-postgres.yaml
#     networks:
#       - miku

# volumes:
#   pg-data:
#   pgadmin-data:

networks:
  miku:
    driver: bridge
